name: On PR
on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]

jobs:
  start-workflow:
    name: run remote workflow
    uses: benlloydjones/actions-test/.github/workflows/pr.yaml@main
